### ISSUE TITLE
module alias wrapper

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mfalesni/python-deprecate#5]
whole modules that have been removed need a delegate that warns about their move

**Comment by jean** [comment]
@RonnyPfannschmidt do you know about https://github.com/zopefoundation/zope.deprecation ? It has this and more. (No `zope.*` dependencies.)

**Comment by RonnyPfannschmidt** [comment]
@jean nope, i will have to investigate that lib trougly

its really a shame they put it into a zope namespace - in my own experiences zope is pretty much a ecosystem distinct from normal python

**Comment by jean** [comment]
> its really a shame they put it into a zope namespace - in my own
> experiences zope is pretty much a ecosystem distinct from normal python

That's a common impression, but it hasn't been true for years. They've done
a lot of work removing unneeded dependencies.

**Comment by RonnyPfannschmidt** [comment]
their brand has been "tainted" in the past, if their libs are no longer dependent on other stuff of that brand they should elevate those libs from that brand

**Comment by RonnyPfannschmidt** [comment]
closing to get off my plate on github
